### ISSUE TITLE
The Smooth Scrollbar is not working with Iframe. Do you have any solution?

### ISSUE THREAD

**Issue by sandeepwebdeveloper** [idiotWu/smooth-scrollbar#485] opened 2022-07-13 16:42 UTC
### Checks

- [ ] Not a duplicate.

### Version

8.7.4

### Description

I am using a registration for in my website. The form comes from external link and I implemented it using <ifram src="slug"></iframe>.

I setup the height and width of the iframe but and when I scroll on iframe the page does not scroll.

Can you help me in it?

Thanks.

### Steps to Reproduce

Not sure what to say here.

**Comment by idiotWu** [comment] 2022-07-13 16:47
Duplicate of #143 and #196?

**Closed** 2022-07-14 15:08 UTC
Labels: duplicate, iframe
