### ISSUE TITLE
Default scroll inside smooth scrollbar

### ISSUE THREAD

**Issue by sweelemk** [idiotWu/smooth-scrollbar#127] opened 2017-12-11 09:38 UTC
## Environment
- Browser: Chome
- Version of smooth-scrollbar: 8.2.5

Hi! 
How to get the default scol operation inside the smooth scrollbar area?

## Online demo
https://codepen.io/sweelemk/pen/eyOWRE

**Comment by idiotWu** [comment] 2017-12-11 10:20
Duplicate of #92

**Comment by sweelemk** [comment] 2017-12-11 10:23
Thx!

**Closed** 2017-12-11 10:23 UTC
Labels: duplicate
